### ISSUE TITLE
🕷️[BUG/CRASH/GLITCH] ...Unable to see or choose dialogue options when using mod 

### ISSUE THREAD

**Issue by Ruarieh** [onnoj/DeusExEchelonRenderer#11] opened 2024-04-21 11:32 UTC
Hi there,

I’m in love with what you have achieved here, so thanks very much for your efforts.

Unfortunately when using the mod, I can no longer see or select dialogue options during cutscenes.

Is this normal?

Thanks

**Comment by onnoj** [comment] 2024-04-21 11:34
Can you include what versions you're using, which level you are in and what cutscene you're talking about, and some screenshots would help.

**Comment by Ruarieh** [comment] 2024-04-21 13:38
V.0.2.0 (although the issue has remained with every update for me.)

It happens with any interact-able conversation, such as this one at the club in Hong Kong. The dialogue choices should be at the bottom of the screen, but they’re not visible.

Is it a compatibility issue with the “Widescreen subtitle fix,” that comes as an option with the Deus Exe launcher? As soon as I play without the new renderer, the issue goes.

Thanks,[
![IMG_2366](https://github.com/onnoj/DeusExEchelonRenderer/assets/167684840/f2baf850-0525-435f-8e5d-d0c2453aca12)
](url)

**Comment by onnoj** [comment] 2024-04-21 14:33
It's probably some kind of combination of settings.
Can you show a screenshot of your Deus Exe settings?

Mine are:
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/4381237/0a78b852-3060-4ff9-8dbc-320f0d078dd0)

**Comment by Ruarieh** [comment] 2024-04-21 15:10
<img width="489" alt="image" src="https://github.com/onnoj/DeusExEchelonRenderer/assets/167684840/e216d8e5-a830-49e6-98ea-f8e506e12a15">

My settings, cheers.

**Comment by Ruarieh** [comment] 2024-04-21 16:05
I just used your exact settings, but still no subtitles/options visible at the bottom of the screen unfortunately

**Comment by onnoj** [comment] 2024-04-21 16:07
Same, I can't reproduce your issue:
![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/4381237/8f61d25e-dd1c-4520-9c0d-d21f3948039f)

**Comment by onnoj** [comment] 2024-04-21 16:08
Do you have any modifications to your rtx.conf? Can you try reinstalling it from a package?

**Comment by Ruarieh** [comment] 2024-04-21 17:38
I have reinstalled all 3 steps of the process, but no change i'm afraid

**Comment by onnoj** [comment] 2024-04-21 19:11
When you press ALT+X and then developer settings, and then 'Reset Settings', do all the visuals reset? (for the worse? Don't click save or you'll have to replace your rtx.conf)

**Comment by onnoj** [comment] 2024-04-21 19:15
Also, do you have any other mods or renderers installed? (Or had installed before)?
I noticed your screenshot is incredibly bright

**Comment by Ruarieh** [comment] 2024-04-21 20:01
When I reset settings via Alt+X, the visuals do reset for the worse sadly - I didn't save. I have used Deus Ex revision in the past, but followed your mod instructions after a fresh install. I turned the brightness way up just to make the screenshot clearer. Thanks

**Comment by onnoj** [comment] 2024-04-29 18:39
Hmm, still can't reproduce it.

When you're in a conversation that's supposed to have black bars, can you open the Remix menu (Alt+X) and browse to "Game Setup", and then categorize all black textures (and textures containing text) as 'UI Textures', and see if the UI pops back in?

![image](https://github.com/onnoj/DeusExEchelonRenderer/assets/4381237/ecc27137-c4d5-4d49-a5eb-a2c1267ef041)

If that fixes it, can you attach your rtx.conf, your DeusEx.ini and System.ini files? (If you're using Deus Exe, they're in the \My Documents\Deus Ex\System folder, otherwise it's the Deus Ex game System folder).

**Comment by onnoj** [comment] 2024-06-03 18:54
Issue cannot be reproduced, and no reply from user. Closing issue, feel free to reopen!

**Closed as not planned by onnoj** 2024-06-03 18:54 UTC
Labels: bug
